[package]
name = "desktop-work-area"
version = "0.1.0"
authors = ["Eric Mitchem <ericmitchem@gmail.com>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["errhandlingapi", "winbase", "winuser"] }
